In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
ranks_file = ["manual_rank_1.xlsx", "manual_rank_2.xlsx", "manual_rank_3.xlsx", "manual_rank_4.xlsx", "manual_rank_5.xlsx", "manual_rank_6.xlsx"]
data_path = "./data/"

In [3]:
rank_data = pd.read_excel(data_path + ranks_file[5])

In [4]:
# 替换列名
rank_data.columns=["id", "index1", "index2", "index3", "index4", "index5", "index6"]

In [5]:
# 指标
indexes = ["index1", "index2", "index3", "index4", "index5", "index6"]

In [6]:
rank_data[indexes] = rank_data[indexes].apply(lambda x: x/10, axis=1)

In [7]:
rank_data.describe()

,id,index1,index2,index3,index4,index5,index6
count,65.000000,65.000000,65.000000,65.000000,65.000000,65.000000,65.000000
mean,100.692308,1.253846,1.346154,0.338462,0.007692,0.115385,1.676923
std,60.868178,0.545744,0.565430,0.251677,0.062017,0.290060,0.454412
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,58.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.500000
50%,90.000000,1.000000,1.500000,0.500000,0.000000,0.000000,2.000000
75%,151.000000,2.000000,2.000000,0.500000,0.000000,0.000000,2.000000
max,204.000000,2.000000,2.000000,1.000000,0.500000,1.000000,2.000000

In [11]:
survey_data = pd.read_excel(data_path + "survey.xlsx")

In [18]:
survey_data.columns = ["id", "role", "job", "industry1", "industry2", "education", "gender", "age", "chatgpt", "sample1", "sample2", "sample3", "sample4", "sample5", "total"]

In [65]:
survey_data

,id,role,job,industry1,industry2,education,gender,age,chatgpt,sample1,sample2,sample3,sample4,sample5,total
0,50,B.其他管理者,C.销售,能源/矿产/环保,电气/电力/水利,D.大学本科,B.女,E.41~50岁,A.是,10,10,10,10,10,10
1,49,C.其他员工,C.销售,商业服务,专业服务/咨询(财会/法律/人力资源等),C.大学专科,B.女,C.25~30岁,A.是,8,9,10,9,10,9
2,48,A.供应链管理者,C.销售,生产/加工/制造,仪器仪表及工业自动化,D.大学本科,A.男,D.31~40岁,A.是,8,6,8,6,8,8
3,47,B.其他管理者,E.其他,房地产/建筑业,房地产/建筑/建材/工程,C.大学专科,B.女,E.41~50岁,A.是,6,6,7,7,6,6
4,46,B.其他管理者,D.公司高层,政府/非盈利机构,政府/公共事业/非盈利机构,D.大学本科,B.女,E.41~50岁,A.是,7,6,7,7,6,6
5,45,C.其他员工,E.其他,政府/非盈利机构,政府/公共事业/非盈利机构,D.大学本科,A.男,E.41~50岁,B.否,7,7,5,7,6,6
6,44,A.供应链管理者,E.其他,生产/加工/制造,加工制造（原料加工/模具）,C.大学专科,A.男,D.31~40岁,A.是,6,8,6,7,10,8
7,43,B.其他管理者,C.销售,贸易/批发/零售/租赁业,零售/批发,D.大学本科,B.女,D.31~40岁,A.是,5,6,6,5,6,5
8,42,C.其他员工,E.其他,商业服务,专业服务/咨询(财会/法律/人力资源等),B.高中/中专/技校,B.女,E.41~50岁,B.否,10,10,8,10,8,9
9,41,A.供应链管理者,A.采购,生产/加工/制造,汽车/摩托车,D.大学本科,B.女,D.31~40岁,A.是,8,7,8,9,9,10
10,40,D.其他,E.其他,贸易/批发/零售/租赁业,零售/批发,B.高中/中专/技校,B.女,D.31~40岁,A.是,10,10,10,10,10,10
11,39,A.供应链管理者,C.销售,生产/加工/制造,医疗设备/器械,B.高中/中专/技校,A.男,D.31~40岁,A.是,10,10,10,10,10,10
12,38,C.其他员工,E.其他,IT/通信/电子/互联网,互联网/电子商务,C.大学专科,A.男,C.25~30岁,B.否,7,8,7,6,8,7
13,37,C.其他员工,D.公司高层,生产/加工/制造,医疗设备/器械,D.大学本科,B.女,D.31~40岁,A.是,7,8,10,8,8,8
14,36,A.供应链管理者,B.生产,能源/矿产/环保,能源/矿产/采掘/冶炼,D.大学本科,A.男,C.25~30岁,A.是,8,8,8,8,8,8
15,35,D.其他,E.其他,文化/传媒/娱乐/体育,媒体/出版/影视/文化传播,D.大学本科,B.女,D.31~40岁,B.否,9,9,8,9,9,9
16,34,C.其他员工,C.销售,IT/通信/电子/互联网,互联网/电子商务,C.大学专科,A.男,B.18~24岁,A.是,6,6,6,5,6,8
17,33,C.其他员工,E.其他,生产/加工/制造,医药/生物工程,D.大学本科,B.女,B.18~24岁,A.是,8,9,8,7,6,8
18,32,C.其他员工,A.采购,生产/加工/制造,加工制造（原料加工/模具）,D.大学本科,B.女,C.25~30岁,A.是,8,7,8,8,7,7
19,31,A.供应链管理者,C.销售,贸易/批发/零售/租赁业,贸易/进出口,C.大学专科,B.女,C.25~30岁,A.是,8,8,10,6,5,9
20,30,A.供应链管理者,A.采购,生产/加工/制造,办公用品及设备,D.大学本科,B.女,D.31~40岁,A.是,10,10,10,10,10,10
21,29,C.其他员工,A.采购,生产/加工/制造,加工制造（原料加工/模具）,C.大学专科,B.女,E.41~50岁,A.是,7,7,8,8,8,8
22,28,C.其他员工,E.其他,房地产/建筑业,物业管理/商业中心,D.大学本科,B.女,E.41~50岁,B.否,4,4,7,7,7,5
23,27,C.其他员工,B.生产,生产/加工/制造,医药/生物工程,D.大学本科,B.女,C.25~30岁,A.是,8,9,8,9,9,9
24,26,B.其他管理者,C.销售,贸易/批发/零售/租赁业,贸易/进出口,D.大学本科,A.男,B.18~24岁,A.是,10,7,8,10,6,8
25,25,C.其他员工,E.其他,生产/加工/制造,仪器仪表及工业自动化,D.大学本科,B.女,C.25~30岁,B.否,8,8,8,8,8,10
26,24,A.供应链管理者,C.销售,房地产/建筑业,房地产/建筑/建材/工程,D.大学本科,A.男,C.25~30岁,A.是,7,6,7,6,6,6
27,23,A.供应链管理者,A.采购,生产/加工/制造,加工制造（原料加工/模具）,D.大学本科,B.女,E.41~50岁,A.是,8,8,7,8,7,8
28,22,B.其他管理者,C.销售,贸易/批发/零售/租赁业,零售/批发,C.大学专科,A.男,E.41~50岁,A.是,7,7,7,7,7,7
29,21,C.其他员工,C.销售,IT/通信/电子/互联网,互联网/电子商务,C.大学专科,B.女,B.18~24岁,B.否,6,5,7,5,7,8
30,20,B.其他管理者,E.其他,政府/非盈利机构,政府/公共事业/非盈利机构,C.大学专科,A.男,C.25~30岁,A.是,7,7,6,7,7,8
31,19,A.供应链管理者,A.采购,政府/非盈利机构,学术/科研,D.大学本科,B.女,C.25~30岁,A.是,6,5,7,6,6,6
32,18,C.其他员工,E.其他,IT/通信/电子/互联网,IT服务(系统/数据/维护),D.大学本科,A.男,D.31~40岁,A.是,7,6,8,8,5,7
33,17,B.其他管理者,E.其他,政府/非盈利机构,政府/公共事业/非盈利机构,D.大学本科,B.女,C.25~30岁,A.是,7,5,8,7,5,5
34,16,A.供应链管理者,B.生产,能源/矿产/环保,石油/石化/化工,E.硕士及以上,B.女,C.25~30岁,A.是,3,2,3,4,5,7
35,15,B.其他管理者,B.生产,生产/加工/制造,仪器仪表及工业自动化,C.大学专科,B.女,C.25~30岁,A.是,10,8,9,8,9,10
36,14,D.其他,E.其他,商业服务,专业服务/咨询(财会/法律/人力资源等),C.大学专科,B.女,B.18~24岁,B.否,7,8,8,8,7,7
37,13,A.供应链管理者,B.生产,贸易/批发/零售/租赁业,贸易/进出口,D.大学本科,B.女,D.31~40岁,A.是,7,5,8,6,8,8
38,12,C.其他员工,A.采购,服务业,旅游/度假,B.高中/中专/技校,B.女,B.18~24岁,A.是,7,6,8,6,5,7
39,11,C.其他员工,C.销售,文化/传媒/娱乐/体育,媒体/出版/影视/文化传播,D.大学本科,B.女,C.25~30岁,A.是,7,7,6,7,7,7
40,10,A.供应链管理者,A.采购,文体教育/工艺美术,教育/培训/院校,C.大学专科,B.女,C.25~30岁,A.是,10,10,10,10,10,10
41,9,B.其他管理者,B.生产,文化/传媒/娱乐/体育,媒体/出版/影视/文化传播,C.大学专科,A.男,C.25~30岁,A.是,8,6,8,6,9,8
42,8,A.供应链管理者,D.公司高层,金融业,保险,E.硕士及以上,B.女,D.31~40岁,A.是,7,4,6,7,8,9
43,7,B.其他管理者,A.采购,贸易/批发/零售/租赁业,零售/批发,C.大学专科,B.女,D.31~40岁,A.是,5,6,7,5,6,7
44,6,C.其他员工,C.销售,服务业,医疗/护理/美容/保健/卫生服务,C.大学专科,B.女,B.18~24岁,B.否,7,7,7,8,6,6
45,5,C.其他员工,C.销售,服务业,医疗/护理/美容/保健/卫生服务,C.大学专科,B.女,E.41~50岁,A.是,7,6,6,5,8,7
46,4,A.供应链管理者,C.销售,文体教育/工艺美术,教育/培训/院校,D.大学本科,B.女,C.25~30岁,A.是,8,7,9,7,8,7
47,3,B.其他管理者,D.公司高层,能源/矿产/环保,能源/矿产/采掘/冶炼,D.大学本科,A.男,E.41~50岁,A.是,8,8,8,8,8,7
48,2,C.其他员工,B.生产,房地产/建筑业,房地产/建筑/建材/工程,D.大学本科,B.女,B.18~24岁,A.是,6,7,6,5,7,6
49,1,C.其他员工,E.其他,IT/通信/电子/互联网,网络游戏,D.大学本科,B.女,D.31~40岁,B.否,8,8,8,8,8,6

In [67]:
survey_data[survey_data["education"] == "D.大学本科"]

,id,role,job,industry1,industry2,education,gender,age,chatgpt,sample1,sample2,sample3,sample4,sample5,total
0,50,B.其他管理者,C.销售,能源/矿产/环保,电气/电力/水利,D.大学本科,B.女,E.41~50岁,A.是,10,10,10,10,10,10
2,48,A.供应链管理者,C.销售,生产/加工/制造,仪器仪表及工业自动化,D.大学本科,A.男,D.31~40岁,A.是,8,6,8,6,8,8
4,46,B.其他管理者,D.公司高层,政府/非盈利机构,政府/公共事业/非盈利机构,D.大学本科,B.女,E.41~50岁,A.是,7,6,7,7,6,6
5,45,C.其他员工,E.其他,政府/非盈利机构,政府/公共事业/非盈利机构,D.大学本科,A.男,E.41~50岁,B.否,7,7,5,7,6,6
7,43,B.其他管理者,C.销售,贸易/批发/零售/租赁业,零售/批发,D.大学本科,B.女,D.31~40岁,A.是,5,6,6,5,6,5
9,41,A.供应链管理者,A.采购,生产/加工/制造,汽车/摩托车,D.大学本科,B.女,D.31~40岁,A.是,8,7,8,9,9,10
13,37,C.其他员工,D.公司高层,生产/加工/制造,医疗设备/器械,D.大学本科,B.女,D.31~40岁,A.是,7,8,10,8,8,8
14,36,A.供应链管理者,B.生产,能源/矿产/环保,能源/矿产/采掘/冶炼,D.大学本科,A.男,C.25~30岁,A.是,8,8,8,8,8,8
15,35,D.其他,E.其他,文化/传媒/娱乐/体育,媒体/出版/影视/文化传播,D.大学本科,B.女,D.31~40岁,B.否,9,9,8,9,9,9
17,33,C.其他员工,E.其他,生产/加工/制造,医药/生物工程,D.大学本科,B.女,B.18~24岁,A.是,8,9,8,7,6,8
18,32,C.其他员工,A.采购,生产/加工/制造,加工制造（原料加工/模具）,D.大学本科,B.女,C.25~30岁,A.是,8,7,8,8,7,7
20,30,A.供应链管理者,A.采购,生产/加工/制造,办公用品及设备,D.大学本科,B.女,D.31~40岁,A.是,10,10,10,10,10,10
22,28,C.其他员工,E.其他,房地产/建筑业,物业管理/商业中心,D.大学本科,B.女,E.41~50岁,B.否,4,4,7,7,7,5
23,27,C.其他员工,B.生产,生产/加工/制造,医药/生物工程,D.大学本科,B.女,C.25~30岁,A.是,8,9,8,9,9,9
24,26,B.其他管理者,C.销售,贸易/批发/零售/租赁业,贸易/进出口,D.大学本科,A.男,B.18~24岁,A.是,10,7,8,10,6,8
25,25,C.其他员工,E.其他,生产/加工/制造,仪器仪表及工业自动化,D.大学本科,B.女,C.25~30岁,B.否,8,8,8,8,8,10
26,24,A.供应链管理者,C.销售,房地产/建筑业,房地产/建筑/建材/工程,D.大学本科,A.男,C.25~30岁,A.是,7,6,7,6,6,6
27,23,A.供应链管理者,A.采购,生产/加工/制造,加工制造（原料加工/模具）,D.大学本科,B.女,E.41~50岁,A.是,8,8,7,8,7,8
31,19,A.供应链管理者,A.采购,政府/非盈利机构,学术/科研,D.大学本科,B.女,C.25~30岁,A.是,6,5,7,6,6,6
32,18,C.其他员工,E.其他,IT/通信/电子/互联网,IT服务(系统/数据/维护),D.大学本科,A.男,D.31~40岁,A.是,7,6,8,8,5,7
33,17,B.其他管理者,E.其他,政府/非盈利机构,政府/公共事业/非盈利机构,D.大学本科,B.女,C.25~30岁,A.是,7,5,8,7,5,5
37,13,A.供应链管理者,B.生产,贸易/批发/零售/租赁业,贸易/进出口,D.大学本科,B.女,D.31~40岁,A.是,7,5,8,6,8,8
39,11,C.其他员工,C.销售,文化/传媒/娱乐/体育,媒体/出版/影视/文化传播,D.大学本科,B.女,C.25~30岁,A.是,7,7,6,7,7,7
46,4,A.供应链管理者,C.销售,文体教育/工艺美术,教育/培训/院校,D.大学本科,B.女,C.25~30岁,A.是,8,7,9,7,8,7
47,3,B.其他管理者,D.公司高层,能源/矿产/环保,能源/矿产/采掘/冶炼,D.大学本科,A.男,E.41~50岁,A.是,8,8,8,8,8,7
48,2,C.其他员工,B.生产,房地产/建筑业,房地产/建筑/建材/工程,D.大学本科,B.女,B.18~24岁,A.是,6,7,6,5,7,6
49,1,C.其他员工,E.其他,IT/通信/电子/互联网,网络游戏,D.大学本科,B.女,D.31~40岁,B.否,8,8,8,8,8,6

In [155]:
sample_data = survey_data[survey_data["education"] == "D.大学本科"][survey_data["id"] != 28][survey_data["id"] != 43][survey_data["id"] != 19][survey_data["id"] != 2][survey_data["id"] != 0][survey_data["id"] != 30]

C:\Users\linji\AppData\Local\Temp\ipykernel_42228\2838957682.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sample_data = survey_data[survey_data["education"] == "D.大学本科"][survey_data["id"] != 28][survey_data["id"] != 43][survey_data["id"] != 19][survey_data["id"] != 2][survey_data["id"] != 0][survey_data["id"] != 30]
C:\Users\linji\AppData\Local\Temp\ipykernel_42228\2838957682.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sample_data = survey_data[survey_data["education"] == "D.大学本科"][survey_data["id"] != 28][survey_data["id"] != 43][survey_data["id"] != 19][survey_data["id"] != 2][survey_data["id"] != 0][survey_data["id"] != 30]
C:\Users\linji\AppData\Local\Temp\ipykernel_42228\2838957682.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sample_data = survey_data[survey_data["education"] == "D.大学本科"][survey_data["id"] != 28][survey_data["id"] != 43][survey_data["id"] != 19][survey_data["id"] != 2][survey_data["id"] != 0][survey_data["id"] != 30]
C:\Users\linji\AppData\Local\Temp\ipykernel_42228\2838957682.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sample_data = survey_data[survey_data["education"] == "D.大学本科"][survey_data["id"] != 28][survey_data["id"] != 43][survey_data["id"] != 19][survey_data["id"] != 2][survey_data["id"] != 0][survey_data["id"] != 30]
C:\Users\linji\AppData\Local\Temp\ipykernel_42228\2838957682.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sample_data = survey_data[survey_data["education"] == "D.大学本科"][survey_data["id"] != 28][survey_data["id"] != 43][survey_data["id"] != 19][survey_data["id"] != 2][survey_data["id"] != 0][survey_data["id"] != 30]
C:\Users\linji\AppData\Local\Temp\ipykernel_42228\2838957682.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sample_data = survey_data[survey_data["education"] == "D.大学本科"][survey_data["id"] != 28][survey_data["id"] != 43][survey_data["id"] != 19][survey_data["id"] != 2][survey_data["id"] != 0][survey_data["id"] != 30]

In [175]:
# 保存sample_data
sample_data.to_excel(data_path + "sample_data.xlsx")

In [147]:
N = sample_data.shape[0]
K = sample_data.shape[1] - 1

In [157]:
N

22

In [148]:
K

5

In [149]:
item_variances = sample_data.var(ddof=1)

In [150]:
cov_sum = 0
for i in range(K):
    for j in range(i+1, K):
        cov_sum += sample_data.iloc[:,i].cov(sample_data.iloc[:,j])

In [151]:
cronbach_alpha = K/(K-1)*(1 - cov_sum/(item_variances.sum() + cov_sum))

In [152]:
cronbach_alpha

0.7041574889867843

In [154]:
sample_data.iloc

In [158]:
data_boat = pd.read_excel(data_path + "2022.xlsx")

In [173]:
data_boat.groupby("company").agg({"profit_rate": "mean"})

                      profit_rate
company
中远海运特种运输股份有限公司           0.014354
中远海运（广州）有限公司海员宾馆         0.008620
佛山三龙湾蓝海豚文旅有限公司           0.009997
宁波汉雅蓝海豚文旅有限公司           -0.488388
广东中威复合材料有限公司-陆岸派遣        0.071642
广东省湛江航运集团有限公司            0.014763
广东省湛江航运集团有限公司船厂-陆岸派遣     0.010890
广东省珠江航运有限公司             -0.241471
广州中远海运滚装运输有限公司           0.012872
广州市瑞港假期旅游有限公司            0.007150
广州蓝海豚游船有限公司              0.008486
海南中远海运沥青运输有限公司           0.015253
海南湛航投资发展有限公司             0.010449